### DISCUSSION TITLE
Welcome to .github Discussions!

### DISCUSSION THREAD

**Discussion by Madib036** [Malesforfemalesllc/.github#1] [Announcements]
[client_secret_126730030461-glitalo307fk8583jh3feibv142gn5gg.apps.googleusercontent.com.json](https://github.com/user-attachments/files/16819114/client_secret_126730030461-glitalo307fk8583jh3feibv142gn5gg.apps.googleusercontent.com.json)

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by Madib036** [comment]


**Reply by Madib036** [reply]
# "hlpxjz7nuu7uulgmgvnk26th67axim4o6s254ylxykbuuudxu57a.mx-verification.google.com."

**Reply by Madib036** [reply]
```

# Template Terraform to deploy to Cloud Infrastructure

# This template allows you to deploy your infrastructure using Terraform to supported cloud providers.
# The workflow allows running tests, security scans on feature branches (as well as master).
# After merging code to master the infrastructure will be deployed to cloud according to the given terraform template.

# Prerequisites: credentials according to used cloud provider.
# For advanced cases, please, follow terraform docs https://www.terraform.io/docs/index.html.


image: hashicorp/terraform

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - terraform init
              - terraform validate
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
  branches:
    master:
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
        - step:
            name: Deploy to Production
            deployment: Production
            trigger: manual
            script:
              - terraform init
              - terraform plan
              - terraform apply -auto-approve

```
